version: "3.5"

volumes:
  data-mysql:
    external: false

services:
  app:
    build:
      context: ./docker/app
      args:
        - PHP_IMAGE=${PHP_IMAGE}
        - APP_DIR=${APP_DIR}
    container_name: app
    user: ${UID}:${GID}
    volumes:
      - ./:/var/www/html
    ports:
      - 9000:9000
      - 8080:8080

  nginx:
    image: ${NGINX_IMAGE}
    container_name: nginx
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - ./:/var/www/html
    ports:
      - ${NGINX_PORT}:80
      - 443:443

  phpmyadmin:
    image: ${PHPMYADMIN_IMAGE}
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      MYSQL_USERNAME: root 
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      PMA_HOST: mysql
      PMA_ARBITRARY: 1
  
  mysql:
    image: ${MYSQL_IMAGE}
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: mysql
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_DATABASE: digitalSeller
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - data-mysql:/var/lib/mysql